spring.application.name=CacheCommerce

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/cache-proj
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

#Redis-cache config
#spring.cache.type=redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379


spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=19689
spring.data.redis.password=${REDIS_PASSWORD}